### ISSUE TITLE
AADSTS50011 Error

### ISSUE THREAD

**Issue by awlnx** [tabs-not-spaces/Intune-App-Deploy#12]
when I try to use the publish task I get the AADSTS50011 error
"The reply URL specified in the request does not match the reply URLs configured for the application"

**Comment by powershellking** [comment]
This issue has something to do with the way Intune-AppDeploy authenticates against Microsoft Graph. The client ID that is provided as default in Intune-AppDeploy is from the old Intune-PowerShell enterprise application that uses the old ADAL standard to authenticate against Microsoft Graph. Itnune AppDeploy instead uses the more modern MSAL standard which requires other redirect URIs to be configured. In order to solve this, I suggest that you create your own app registration in Azure for that purpose. Therefore follow these steps:

1. Go to https://portal.azure.com and sign in with a user that has at least application administrator privileges.
2. Go to Azure Active Directory
3. Click on App registrations.
4. Select New registration.
5. Give your application a meaningful name.
6. Depending on your use case select single or multi-tenant app. (Allowing personal accounts in my opinion doesn't make sense because personal accounts can't use Intune afaik.
7. At this point leave the redirect URI blank and click Register. The redirect URI will be added later on.
8. Now go to authentication and click Add a platform.
9. Select mobile and desktop applications and tick the redirect URL https://login.microsoftonline.com/common/oauth2/nativeclient and click configure.
10. Next go to API permissions and click Add a permission.
11. Navigate to Microsoft Graph --> Delegated permissions.
12. Expand DeviceManagementApps and tick DeviceManagementApps.ReadWriteAll and click Add permission. This is the minimum required permission to create apps. If you're planning to use more of @tabs-not-spaces 's great tools you might want to visit his website here for additional required permissions: https://powers-hell.com/2020/06/28/managing-intune-with-graph-powershell-7-msal/. When you're finished click on configure.
13. Next important thing is to grant the admin consent. Therefore click on Grant admin consent for <your tenant name> and confirm by clicking on yes.
14. Now go back to the overview page of the app registration you just created. There you'll find the client ID which is required for authentication. Copy it and replace the old client ID in the function Get-AuthToken (file tasks/Deploy.functions.ps1) with your new one.

Now the authentication should work as expected.

**Comment by awlnx** [comment]
That did work.
Thanks.
